[package]
name = "rust-query-engine-greatest"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion-expr = { path = "datafusion/datafusion/expr" }
datafusion-common = { path = "datafusion/datafusion/common" }
datafusion-physical-expr = { path = "datafusion/datafusion/physical-expr" }
pyo3 = { version = "0.22", features = ["extension-module", "auto-initialize"] }
datafusion = "42.0.0"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
debug = true
lto = true

[lib]
name = "rust_query_engine_greatest"
path = "src/lib.rs"

[[bin]]
name = "rust-query-engine-greatest"
path = "src/main.rs"